# This is a basic workflow to help you get started with Actions

name: Deploy SecCopilot

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.JLSECRET }}
          # subscription: 'your-subscription-id'
          
      - name: Install Bicep CLI
        run: |
          curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          chmod +x ./bicep
          mkdir -p ~/.azure/bin
          mv ./bicep ~/.azure/bin/
          echo "## Add Bicep binary to PATH"
          echo "~/.azure/bin" >> $GITHUB_PATH
      
      # Runs a set of commands using the runners shell
      - name: Deploy SecCopilot
        
        run: |
          az group create -l westeurope -n JLCopilot
          az deployment group create --name CopilotDeployment --resource-group JLCopilot --template-file ./main.bicep --parameters ./main.bicepparam
