# This is a basic workflow to help you get started with Actions

name: Remove SecCopilot

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Schedule the workflow to run once every day at midnight (UTC)
  schedule:
    - cron: '0 0 * * *'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.JLSECRET }}
      # Runs a set of commands using the runners shell
      - name: Remove SecCopilot
        run: |
          az group delete --name JLCopilot --yes --no-wait